### ISSUE TITLE
Linux: Orature 1.0.0 freezes when clicking "View Logs"

### ISSUE THREAD

**Issue by PurpleGuitar** [Bible-Translation-Tools/otter#465]
To reproduce:

1. Start Orature.
2. Click the "Info" button in the sidebar.
3. Click the "View Logs" button.
4. Observe that Orature freezes.

![image](https://user-images.githubusercontent.com/1095575/146821935-b17731bc-2d37-4b10-a4a8-0ab1491f731a.png)

---
$ cat /etc/os-release
NAME="Linux Mint"
VERSION="20.2 (Uma)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 20.2"
VERSION_ID="20.2"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=uma
UBUNTU_CODENAME=focal

**Comment by AnonymousWalker** [comment]
Thank you @PurpleGuitar, we got it fixed and merged

**Comment by PurpleGuitar** [comment]
Confirmed fixed in 1.0.1_2751.  Thanks!
