### ISSUE TITLE
Add ability to update target language codes

### ISSUE THREAD

**Issue by mondele** [Bible-Translation-Tools/otter#590]
Orature needs the ability to update language codes from td without invoking a new build. Alternatively, the ability to manually edit the list of language codes would be welcome. Finally, another possibility would be to allow the use of arbitrary language codes (since the code is only entered once per machine per project.)

**Comment by jsarabia** [comment]
Languages can be updated from the settings page

(This has been added a while ago for both Orature 1.0 and 3.0, unsure of which PR added this)
