### ISSUE TITLE
change color of play audio button

### ISSUE THREAD

**Issue by ChrisJarka** [Bible-Translation-Tools/otter#696]
Have you considered changing the color of the play source audio button as an additional visual prompt to the end user?
I see that the play triangle does become a pause icon and that the button has a more emphasized edge - but maybe changing the color or make the intensity/shade a bit more different - might reinforce the difference?

![play source button](https://user-images.githubusercontent.com/9850185/199820020-9ea3a788-d5f0-4e17-b552-61ea73b1cc1a.jpg)

![play source button idea](https://user-images.githubusercontent.com/9850185/199820064-ceddea35-9305-4627-99f0-2a2740e95bf5.jpg)

**Comment by AnonymousWalker** [comment]
great suggestion! We added the color difference in the new Orature 3 release
![image](https://github.com/Bible-Translation-Tools/Orature/assets/34975907/54614a46-61f1-4709-8179-75cd0fea03f5)
