### ISSUE TITLE
Information on 'Takes' screen

### ISSUE THREAD

**Issue by ChrisJarka** [Bible-Translation-Tools/otter#697]
Has there been discussion on having the length of the take on the takes screen?
As an end user I find it helpful to know date and time of when a recording was made. I would also find it helpful to know the length of the recordings.
Case in point.... These recordings look the same length to me but in fact one is 30 seconds long and the other is over 2 minutes long. Knowing that would make it an easy decision on which should be thrown away.
![chapter takes](https://user-images.githubusercontent.com/9850185/201494578-1cefeba1-c690-4254-bb6b-09380de079bf.png)

**Comment by jsarabia** [comment]
Closing as the UI has changed with Orature 3.0
