### ISSUE TITLE
Functionality to manage source texts updates

### ISSUE THREAD

**Issue by sea-liesch** [Bible-Translation-Tools/otter#750]
Currently the list of available source languages is not updatable without updating Orature to the latest release.

1.)  Is it possible to add functionality to update the source text without having to download and reinstall Orature?
2.)  If not, could there be an "Update source text" button that could check if a new source text has been released and then instruct the user how to then proceed.

**Comment by jsarabia** [comment]
@sea-liesch Source Languages can already be updated. Only English is bundled with Orature by default. To import source, download from Audio.BIEL or WACS repos, and import them.

Some older versions of Orature will require backing up existing projects made from the source you are updating and deleting these projects from Orature first. Once the source is updated, you can re-import the backed up projects.
