### ISSUE TITLE
Navigation Freezing

### ISSUE THREAD

**Issue by ChrisJarka** [Bible-Translation-Tools/otter#804]
Version 1.9.1+6281
When going from the chapter screen back to the book screen my program blanks out.
I would like to navigate from a chapter to the next chapter but did not find a navigation button. So, I clicked on the book name in the header. The screen basically went blank. 
My solution to get out of that predicament was that I needed to click on the project button and then I could click on the book button and then make the chapter choice that I wanted.
Could a more simpler way to navigate between chapters of a book be created? 

https://github.com/Bible-Translation-Tools/Orature/assets/9850185/6cefcd48-79b4-4bbf-9d2e-a19a58a94216

**Comment by jsarabia** [comment]
Closing as the UI has changed with Orature 3.0
