### ISSUE TITLE
Source & Target language info inside project screens

### ISSUE THREAD

**Issue by mondele** [Bible-Translation-Tools/otter#809]
When working with several languages, it is possible to open a project that is not the one you intended. Once you leave the Project screen, you no longer can see which languages are involved in the current project. Thus, it is easy to record in the wrong language for the project, especially if you have several projects with the same source.

As a user, I would like the source and target languages displayed in the top bar of the screen when I'm working inside the project.
![Selection_001](https://github.com/Bible-Translation-Tools/Orature/assets/25468552/5925bf62-dda4-4260-9b7c-b00f87c4df9e)
![Selection_002](https://github.com/Bible-Translation-Tools/Orature/assets/25468552/75a120a2-28f8-431b-b7f0-e199dadd320a)

**Comment by jsarabia** [comment]
Closing as the UI has changed with Orature 3.0
