### ISSUE TITLE
Build fails for JDK 13+

### ISSUE THREAD

**Issue by mbr4477** [Bible-Translation-Tools/otter#967]
All tested on macOS Sonoma 14.2.1 (23C71) M3 (aarch64).

## JDK 13+ Issues
Thanks to a new function signature for `java.nio.file.FileSystems.newFileSystem` (see [JDK 13 release notes](https://www.oracle.com/java/technologies/javase/13-relnote-issues.html)), compilation fails for `jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/domain/resourcecontainer/project/ZipEntryTreeBuilder.kt` because the second argument `null` is now ambiguous.

### To Reproduce
Install JDK >= 13 and <= 20. Follow the readme instruction to install and run. The build will fail with an error like this:

```
e: <path>/Orature/jvm/workbookapp/src/main/kotlin/org/wycliffeassociates/otter/jvm/workbookapp/domain/resourcecontainer/project/ZipEntryTreeBuilder.kt:38:28 Overload resolution ambiguity: 
public open fun newFileSystem(p0: Path!, p1: ClassLoader!): FileSystem! defined in java.nio.file.FileSystems
public open fun newFileSystem(p0: Path!, p1: (Mutable)Map<String!, *>!): FileSystem! defined in java.nio.file.FileSystems
```

## JDK 21 Issues
In addition, builds fail on JDK 21 thanks to [this issue](https://youtrack.jetbrains.com/issue/KT-60507/Kapt-IllegalAccessError-superclass-access-check-failed-using-java-21-toolchain) which may only be fixed in Kotlin 2.0.

### To Reproduce
Install JDK 21. Follow the readme instructions to install and run. The build will fail with an error like this:
```
e: java.lang.IllegalAccessError: superclass access check failed:
class org.jetbrains.kotlin.kapt3.base.javac.KaptJavaCompiler (in unnamed module @0x531ecf7)
cannot access class com.sun.tools.javac.main.JavaCompiler (in module jdk.compiler)
because module jdk.compiler does not export com.sun.tools.javac.main to unnamed module @0x531ecf7
```

**Comment by jsarabia** [comment]
Fixed with #1074
